server:
  port: 9191

spring:
  application:
    name: API-GATEWAY
  cloud:
    gateway:
      routes:
        - id: DEPARTMENT-SERVICE
          uri: lb://department-service
          predicates:
            - Path=/Departments/**
        - id: USER-SERVICE
          uri: lb://user-service
          predicates:
              - Path=/Users/**


eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      default-zone: http://localhost:8761/eureka/
  instance:
    hostname: localhost